[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "pokemon-dex"
version = "0.2.0"
description = "JacobS personal Pokemon database and Pokedex for Linux."
requires-python = ">=3.11"
dependencies = [
    "pygame>=2.6.1,<3.0",
]

[project.scripts]
pokemon-dex = "pokemon_dex.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
